name: Check dependencies
on:
  pull_request:
jobs:
  check-dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install -g npm@7
      - uses: hata6502/no-broken-dependency-action@v5
